# -*- coding: utf-8 -*-
"""extract_cls.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a26fT7hBZvNzdbzNuHZ-S0EEr-yVAEfq
"""

#import os
#os.environ['CUDA_VISIBLE_DEVICES'] = "1"
import torch
from transformers import AutoTokenizer, AutoModel

model = AutoModel.from_pretrained('dbmdz/bert-base-italian-cased')
tokenizer = AutoTokenizer.from_pretrained('dbmdz/bert-base-italian-cased')

sentences = ["Mario non è ancora arrivato.","Sono in ritardo."] # list of sentences

batch_encoded = tokenizer.batch_encode_plus(sentences, padding=True, add_special_tokens=True, return_tensors="pt")

with torch.no_grad():
  tokens_outputs = model(**batch_encoded)

cls_encodings = tokens_outputs.last_hidden_states[:,0,:]